name: Sphinx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install gettext
      - run: pip install -r requirements.txt # venv の pip をすべてインストール
      - name: sphinx build(ja)
        run: sphinx-build source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build # sphinx の出力を gh-pages branch に送り込む
